apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: baz-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: baz
    server: https://kubernetes.default.svc
  project: default
  source: 
    repoURL : git@github.com:patiupe/lesson-158.git
    targetRevision: HEAD
    path: environments/staging/baz-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=false
    - Validate=true
    - PrunePropagationPolicy=Foreground
    - PruneLast=true